### PR TITLE
Change function Verb and Add PowerShell 7 ready

### PR DESCRIPTION
**Pull request by JM2K69**
According to PowerShell Verb I change All verb for the module and I make It fully functional with PowerShell 7

In this PR I change this $PSversionTable change -eq to -le

### CODE REVIEW

**Comment by mgreenegit** [comment]
@gehuang-dut @nitinbps

**Review by nitinbps — APPROVED** [review]
:shipit:

**Comment by MKletz** [comment]
Happy to see this change! Would it be wise to create an alias to preserve backwards compatibility?

**Comment by mgreenegit** [comment]
@JM2K69 before we merge, the suggestion from @MKletz is a good one. Can you please add aliases as needed so existing scripts continue functioning? I believe aliases can use unapproved verbs.

cc @nitinbps just for fyi (and thank you for the code review)

**Comment by mgreenegit** [comment]
I want to get this shipped ASAP so I'm creating a "prerelease" branch and merging. I'll take care of the administrative steps like versioning, and I will setup a build pipeline to sign this module before it reaches the gallery. Hopefully will be done today, if not, very soon.

**Comment by JM2K69** [comment]
Hi guys do you have a timeline when the update will be release on the Powershell gallery ?

**Comment by mgreenegit** [comment]
@JM2K69 thank you for the accountability. I published the prerelease branch as "1.0.0-prerelease" in the gallery just now. It may be days before I can get a new pipeline setup and get it signed using a MS cert. After that, unless you see issues I will publish as stable.

**Pull request merged**
